from create_character import CreateCharacter as cc
instance = cc("name", "Class", 1)
instance_2 = cc("Name", "classtype", 10)
print(instance.getname())
print(instance.getclass())
print(instance.getlevel())
print(instance_2.getname())
print(instance_2.getclass())
print(instance_2.getlevel())
instance.set_name("A")
instance.set_class("A")
instance.set_level(2)
instance_2.set_name("B")
instance_2.set_class("B")
instance_2.set_level(20)
print(instance)
print(instance_2)